package com.votaciones.api.audit.domain

enum class AuditAction {
    LOGIN,
    REGISTER,
    USER_STATUS_CHANGED,
    USER_ROLES_CHANGED,
    TOURNAMENT_CREATED,
    TOURNAMENT_UPDATED,
    TOURNAMENT_STATUS_CHANGED,
    PARTICIPANT_CREATED,
    PARTICIPANT_UPDATED,
    PARTICIPANT_DELETED,
    ROUND_CREATED,
    ROUND_UPDATED,
    ROUND_OPENED,
    ROUND_CLOSED,
    ROUND_PROCESSED,
    RESULTS_PUBLISHED,
    MATCH_CREATED,
    MATCH_WINNER_REGISTERED,
    VOTE_CAST,
}
